### PR TITLE
Added support for _supportedLayout

### LINKED ISSUE #45: _supportedLayout attribute needs adding to schema
This is to help the authoring tool determine layout styles for this component

### PR DESCRIPTION
**Pull request by darylhedley**
Fixes #45

### CODE REVIEW

**Comment by dennis-learningpool** [comment]
+1

**Comment by dancgray** [comment]
Does "default": "half-width" restrict layout choice in the editor? If so this seems a bit limiting.

**Comment by taylortom** [comment]
+1 (@dancgray I'm assuming that's just what's selected by default, as all are included in the enum)

**Comment by dancgray** [comment]
+1

**Pull request merged**
