### PR TITLE
Missing semantic differentiation between status and heading

### LINKED ISSUE #118: Missing semantic differentiation between status and heading
## Bug Description:
After an accordion item has been visited, "visited" text is included in the item title without semantic differentiation. This can render understanding of the item title unclear for screen reader users.

## Expected Behavior:

- Update the accordion label to include its updated state after it has been visited (ex: Lists (visited))
- Add a checkmark icon to visually indicate the updated state of the item.

### PR DESCRIPTION
**Pull request by swashbuck**
fixes #118 

- Change plus icon to checkmark once the item has been visited.
- Use visited instead of complete/incomplete

### CODE REVIEW

**Comment by oliverfoster** [comment]
Could I have a rationale for the parentheses please? How does it change the way the screen reader reads?

**Comment by swashbuck** [comment]
> Could I have a rationale for the parentheses please? How does it change the way the screen reader reads?

The company that did our external accessibility testing recommended using parentheses to ensure that there's a pause in the screenreader's reading.  Some screenreaders (JAWS maybe?) will sort of skip over commas or semicolons.  Periods may be sufficient, though, and we could do some further testing if that's preferred?

**Comment by joe-replin** [comment]
> Could I have a rationale for the parentheses please? How does it change the way the screen reader reads?

Hello, we've tried a few configurations including a semi-colon. Here's the quote from the testing that came back to us.

> The addition of the semi-colon to the table of contents heading has inconsistent output with different screen readers. JAWS announces the status as "complete semicolon, [Course Title]", while NVDA announces the semicolon with a slight pause that does not make the semantic distinction as clear.
> In addition, the text complete by itself at the beginning of the heading can still make the purpose of the heading misleading without additional context. Consider moving status text to the end of the heading with context as to what the status represents (ex"[Course Title], course completed")

Additionally, the 'status parenthesis' was approved and committed to headings.hbs in core. We were looking to normalize this structure across the individual component items as well.

**Comment by oliverfoster** [comment]
I mean. I strongly disagree with the whole notion of moving it to the back as it dramatically slowly down completion checking in a course. If, for example, I'm navigation with the "H" key, to iterate back and forth through the headers, I now have to wait for each header to read before I can determine its completion status, hugely elongating the time required to determine what I have / haven't completed, it's almost inverse to the visual appearance.

Adding an extra pause with parenthesis is mind blowing to me.

Standardising it is a good idea. If adding parenthesis gives an intended pause, then that's fine, I'm just curious.

**Review by oliverfoster — APPROVED** [review]

**Comment by swashbuck** [comment]
I know that it was recommended to use parentheses, but it seems that periods pause more consistently across screenreaders.  JAWS actually reads out the parentheses, which seems odd since we're just trying to add a pause.  What is everybody's opinion on this?

https://www.deque.com/blog/dont-screen-readers-read-whats-screen-part-1-punctuation-typographic-symbols/

parenthesis
period

**Comment by oliverfoster** [comment]
You'd need to test a double period. The content may end with a period, if you're adding another in the template then it'll have two before the status.

**Comment by swashbuck** [comment]
I've reverted the following changes:

- Switch aria-label to visited status instead of complete/incomplete.
- Move visited status after item title and wrap in parentheses when it exists.

Then, I've added period after the status so that it reads:

[status]. [title]

**Comment by oliverfoster** [comment]
you need to do the complete/incomplete > visited conversion

**Review by oliverfoster — APPROVED** [review]

**Pull request merged**
