### PR TITLE
body content graphics configured in json

### PR DESCRIPTION
**Pull request by kirsty-hames**

### CODE REVIEW

**Comment by oliverfoster** [comment]
+1

**Comment by zenduo** [comment]
Nice addition, Visually would the image appearing first not be nicer?
+1 for code review

**Comment by taylortom** [comment]
+1

Paul W requested that we show the text first by default, as the image is generally passive from an instructional design point of view (i.e. the text requires the attention of the learner first).

**Comment by hrajotia** [comment]
:+1: 

I think [this line](https://github.com/adaptlearning/adapt-contrib-accordion/blob/graphic_config/js/adapt-contrib-accordion.js#L23) needs updating too -
```
if(this.model.get('_graphic')) {
    this.$('.accordion-widget').imageready(_.bind(function() {
        this.setReadyStatus();
    }, this));
} else {
    this.setReadyStatus();
}
```

**Comment by brian-learningpool** [comment]
Can we update the `properties.schema` file too for compatibility with the authoring tool on this?

**Comment by dancgray** [comment]
+1 needs example.json and readme updating

**Comment by taylortom** [comment]
+1, properties.schema will be updated prior to release/merge with master.

**Comment by oliverfoster** [comment]
+1

**Pull request merged**
