### PR TITLE
updating template to add classes to items

### PR DESCRIPTION
**Pull request by ciaranlp**

### CODE REVIEW

**Comment by brian-learningpool** [comment]
+1

**Comment by chucklorenz** [comment]
+1 - Really like the idea. @ciaranlp may I ask that you also update the example.json and the README

**Comment by ciaranlp** [comment]
Hi @chucklorenz the README and the example.json have both been updated.

**Comment by moloko** [comment]
+1 looks great but unfortunately you have a merge conflict...

**Pull request merged**
