### PR TITLE
Test folder hs been removed

### PR DESCRIPTION
**Pull request by belal-almassri-spongeuk**

### CODE REVIEW

**Comment by moloko** [comment]
Travis CI building failing I think because you need to remove karma.conf.js as well? (though that doesn't explain why it's passing for contrib-slider...)

**Comment by belal-almassri-spongeuk** [comment]
Thanks @moloko  this has been done.

**Comment by hrajotia** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by dancgray** [comment]
+1

**Pull request merged**
